

import "bootstrap/dist/css/bootstrap.min.css";

import type { Metadata } from "next";
import { Navbar } from "./components/Navbar/Navbar";

export const metadata: Metadata = {
  title: "Wa Loja",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body>
        <Navbar/>
        {children}
        </body>
    </html>
  );
}
