FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y nginx
ARG PORTA_ARG 
EXPOSE ${PORTA_ARG}
CMD ["nginx", "-g", "daemon off;"] 

# docker build -t server-nginx --build-arg=7000 .
# docker run -d --name primeiroserver -p 7000:80 server-nginx
