FROM ubuntu:latest
RUN apt-get update
RUN apt-get install -y nginx

RUN sed -i 's/listen 80 default_server;/listen 7000 default_server;/' /etc/nginx/sites-available/default 
EXPOSE 7000

CMD ["nginx", "-g", "daemon off;"] 




# sudo docker build -t meuservidor-nginx . 
# sudo docker run -d --name primeiroserver -p 7000:7000 meuservidor-nginx
